# Generated by Django 2.2.19 on 2021-12-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211211_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
