# Generated by Django 2.2.16 on 2022-02-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220204_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date', '-pk'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
